version: '3'
services:
  #API Service
  api:
    build:
      context: ./
      dockerfile: api.dockerfile
    image: app
    expose: 
      - "80"
      - "6001"
    ports:
      - "3030:80"
      - "3031:6001"
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: production
    working_dir: /var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
